name: EPBot CD

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script_stop: true
        script: |
          docker stop ep_bot_container || true \
            && docker rm ep_bot_container || true
          docker build \
            --ssh default=./.ssh/id_rsa \
            -t chapardev/ep_bot \
            git@github.com:ChaPerx64/EnglishPolicemanBot.git
          docker run \
            --name ep_bot_container \
            --env-file './bots/ep_bot/.env.prod' \
            --mount source=ep_bot_volume,target=/db \
            --restart unless-stopped \
            -d \
            chapardev/ep_bot
          docker image prune -f
