name: EPBot CD

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          pkill -f EnglishPolicemanBot.py
          cd "/root/bots/EnglishPolicemanBot"
          git pull origin main
          git status
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          nohup python3 "EnglishPolicemanBot.py" >/dev/null 2>&1 &
